# Generated by Django 5.2.1 on 2025-06-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0002_yelpoauthstate_yelptoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="yelpoauthstate",
            name="state",
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="yelptoken",
            name="business_id",
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
