# Generated by Django 5.2.1 on 2025-06-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0003_alter_yelpoauthstate_state_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoResponseSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_id",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "message",
                    models.TextField(
                        default="Thank you for your message! We will get back to you shortly."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
