# Generated by Django 5.2.1 on 2025-06-09 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webhooks", "0004_autoresponsesettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autoresponsesettings",
            name="business_id",
        ),
    ]
