# Generated by Django 5.2.1 on 2025-06-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0005_remove_autoresponsesettings_business_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoresponsesettings',
            name='access_token',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
