# Generated by Django 5.2.1 on 2025-06-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0006_autoresponsesettings_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(db_index=True, max_length=128)),
                ('lead_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
