# Generated by Django 5.2.3 on 2025-06-11 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0007_processedlead'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(db_index=True, max_length=64)),
                ('content', models.TextField()),
                ('interval_minutes', models.PositiveIntegerField()),
                ('next_run', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledMessageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=16)),
                ('error', models.TextField(blank=True, null=True)),
                ('scheduled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='webhooks.scheduledmessage')),
            ],
        ),
    ]
