# Generated by Django 5.2.3 on 2025-06-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0008_scheduledmessage_scheduledmessagehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoresponsesettings',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='autoresponsesettings',
            name='message',
        ),
        migrations.RemoveField(
            model_name='autoresponsesettings',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='autoresponsesettings',
            name='greeting_template',
            field=models.TextField(default='Hello{sep}{name}! Thank you for your inquiry regarding “{jobs}”.', help_text='Шаблон повідомлення з плейсхолдерами {name}, {jobs}, {sep}'),
        ),
        migrations.AddField(
            model_name='autoresponsesettings',
            name='include_jobs',
            field=models.BooleanField(default=True, help_text='Вмикати вставку списку робіт'),
        ),
        migrations.AddField(
            model_name='autoresponsesettings',
            name='include_name',
            field=models.BooleanField(default=True, help_text='Вмикати вставку імені клієнта'),
        ),
        migrations.AlterField(
            model_name='autoresponsesettings',
            name='access_token',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
