# Generated by Django 5.2.3 on 2025-06-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0009_remove_autoresponsesettings_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoresponsesettings',
            name='follow_up_delay',
            field=models.PositiveIntegerField(default=2, help_text='Затримка перед відправкою follow-up у хвилинах'),
        ),
        migrations.AddField(
            model_name='autoresponsesettings',
            name='follow_up_template',
            field=models.TextField(default='Just checking back in{sep}{name} — do you have any other questions about “{jobs}”?', help_text='Шаблон follow-up повідомлення з плейсхолдерами {name}, {jobs}, {sep}'),
        ),
        migrations.AlterField(
            model_name='autoresponsesettings',
            name='access_token',
            field=models.CharField(help_text='Yelp API access token', max_length=200),
        ),
        migrations.AlterField(
            model_name='autoresponsesettings',
            name='enabled',
            field=models.BooleanField(default=False, help_text='Увімкнути/вимкнути автoвідповіді'),
        ),
        migrations.AlterField(
            model_name='autoresponsesettings',
            name='greeting_template',
            field=models.TextField(default='Hello{sep}{name}! Thank you for your inquiry regarding “{jobs}”.', help_text='Шаблон першого повідомлення з плейсхолдерами {name}, {jobs}, {sep}'),
        ),
        migrations.AlterField(
            model_name='autoresponsesettings',
            name='include_jobs',
            field=models.BooleanField(default=True, help_text='Включати список робіт у вітальне повідомлення'),
        ),
        migrations.AlterField(
            model_name='autoresponsesettings',
            name='include_name',
            field=models.BooleanField(default=True, help_text='Включати ім’я клієнта у вітальне повідомлення'),
        ),
    ]
