# Generated by Django 5.2.3 on 2025-06-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0010_autoresponsesettings_follow_up_delay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoresponsesettings',
            name='refresh_token',
            field=models.CharField(blank=True, help_text='Yelp API refresh token (дійсний 365 днів)', max_length=200),
        ),
        migrations.AddField(
            model_name='autoresponsesettings',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, help_text='Коли access_token перестане бути дійсним', null=True),
        ),
    ]
