# Generated by Django 5.2.3 on 2025-06-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0011_autoresponsesettings_refresh_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('lead_id', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(max_length=32)),
                ('user_type', models.CharField(max_length=32)),
                ('user_id', models.CharField(max_length=64)),
                ('user_display_name', models.CharField(blank=True, max_length=100)),
                ('text', models.TextField(blank=True)),
                ('cursor', models.CharField(blank=True, max_length=128)),
                ('time_created', models.DateTimeField()),
                ('raw', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
