# Generated by Django 5.2.3 on 2025-06-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0012_leadevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('business_id', models.CharField(max_length=64)),
                ('conversation_id', models.CharField(blank=True, max_length=64)),
                ('temporary_email_address', models.EmailField(blank=True, max_length=200)),
                ('temporary_email_address_expiry', models.DateTimeField(blank=True, null=True)),
                ('time_created', models.DateTimeField()),
                ('last_event_time', models.DateTimeField(blank=True, null=True)),
                ('user_display_name', models.CharField(blank=True, max_length=100)),
                ('project', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
