# Generated by Django 5.2.3 on 2025-06-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0013_leaddetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoresponsesettings',
            name='export_to_sheets',
            field=models.BooleanField(default=False, help_text='Записувати нові ліди в Google Sheets'),
        ),
    ]
