# Generated by Django 5.2.3 on 2025-06-19 13:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0014_autoresponsesettings_export_to_sheets'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Лаконічна назва шаблону', max_length=100)),
                ('template', models.TextField(help_text='Текст з плейсхолдерами: "{name}", "{jobs}", "{sep}"')),
                ('delay', models.DurationField(default=datetime.timedelta(days=1), help_text='Затримка перед першим follow-up (наприклад, 24h)')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='autoresponsesettings',
            name='follow_up_delay',
        ),
        migrations.RemoveField(
            model_name='autoresponsesettings',
            name='follow_up_template',
        ),
        migrations.RemoveField(
            model_name='scheduledmessage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='scheduledmessage',
            name='interval_minutes',
        ),
        migrations.AlterField(
            model_name='scheduledmessage',
            name='next_run',
            field=models.DateTimeField(help_text='Час наступного запуску повідомлення'),
        ),
        migrations.AddField(
            model_name='scheduledmessage',
            name='template',
            field=models.ForeignKey(default=1, help_text='Який шаблон FollowUpTemplate використати', on_delete=django.db.models.deletion.CASCADE, to='webhooks.followuptemplate'),
            preserve_default=False,
        ),
    ]
