# Generated by Django 5.2.3 on 2025-06-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0015_followuptemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoresponsesettings',
            name='follow_up_delay',
            field=models.PositiveIntegerField(default=2, help_text='Затримка перед follow-up, в секундах'),
        ),
        migrations.AddField(
            model_name='autoresponsesettings',
            name='follow_up_template',
            field=models.TextField(default='Just checking back in{sep}{name} — any questions about “{jobs}”?', help_text='Шаблон follow-up повідомлення з плейсхолдерами {name}, {jobs}, {sep}'),
        ),
    ]
