# Generated by Django 5.2.3 on 2025-06-19 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0016_autoresponsesettings_follow_up_delay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(db_index=True, max_length=64)),
                ('content', models.TextField(help_text='Текст повідомлення')),
                ('interval_minutes', models.PositiveIntegerField(help_text='Інтервал у хвилинах')),
                ('next_run', models.DateTimeField(help_text='Час наступного виконання')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadScheduledMessageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(help_text="'success' або 'error'", max_length=16)),
                ('error', models.TextField(blank=True, help_text='Текст помилки, якщо є', null=True)),
                ('scheduled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='webhooks.leadscheduledmessage')),
            ],
        ),
    ]
