# Generated by Django 5.2.3 on 2025-07-02 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0038_phone_available_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoresponsesettings',
            name='follow_up_open_from',
            field=models.TimeField(default=datetime.time(8, 0), help_text='Час початку робочих годин для built-in follow-up (локальний час)'),
        ),
        migrations.AlterField(
            model_name='autoresponsesettings',
            name='follow_up_open_to',
            field=models.TimeField(default=datetime.time(20, 0), help_text='Час завершення робочих годин для built-in follow-up (локальний час)'),
        ),
        migrations.AlterField(
            model_name='autoresponsesettings',
            name='greeting_open_from',
            field=models.TimeField(default=datetime.time(8, 0), help_text='Час початку робочих годин для привітання (локальний час)'),
        ),
        migrations.AlterField(
            model_name='autoresponsesettings',
            name='greeting_open_to',
            field=models.TimeField(default=datetime.time(20, 0), help_text='Час завершення робочих годин для привітання (локальний час)'),
        ),
        migrations.AlterField(
            model_name='followuptemplate',
            name='open_from',
            field=models.TimeField(default=datetime.time(8, 0), help_text='Час початку робочих годин (локальний час)'),
        ),
        migrations.AlterField(
            model_name='followuptemplate',
            name='open_to',
            field=models.TimeField(default=datetime.time(20, 0), help_text='Час закінчення робочих годин (локальний час)'),
        ),
    ]
