# Generated by Django 5.2.3 on 2025-07-02 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0039_alter_autoresponsesettings_follow_up_open_from_and_more'),
        ('webhooks', '0039_leaddetail_temp_email_nullable'),
    ]

    operations = [
    ]
