# Generated by Django 5.2.3 on 2025-07-02 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0040_leadevent_cursor_textfield'),
        ('webhooks', '0040_merge_20250702_0801'),
    ]

    operations = [
    ]
