# Generated by Django 5.2.3 on 2025-07-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0041_follow_up_template_blank'),
        ('webhooks', '0041_merge_20250702_0811'),
    ]

    operations = [
    ]
