# Generated by Django 5.2.3 on 2025-07-02 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0042_autoresponsesettings_off_hours_template'),
        ('webhooks', '0042_merge_20250702_1100'),
    ]

    operations = [
    ]
