# Generated by Django 5.2.3 on 2025-07-03 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0043_merge_20250702_2215'),
        ('webhooks', '0043_remove_autoresponse_tokens'),
    ]

    operations = [
    ]
