# Generated by Django 5.2.3 on 2025-07-03 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0044_leaddetail_phone_in_additional_info'),
        ('webhooks', '0044_merge_20250703_1121'),
    ]

    operations = [
    ]
