# Generated by Django 5.2.3 on 2025-07-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0045_leaddetail_phone_number'),
        ('webhooks', '0045_merge_20250703_1328'),
    ]

    operations = [
    ]
