# Generated by Django 5.2.3 on 2025-07-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0046_merge_20250707_1304'),
        ('webhooks', '0046_scheduledmessage_unique'),
    ]

    operations = [
    ]
