# Generated by Django 5.2.4 on 2025-07-14 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0047_leadscheduledmessage_unique'),
        ('webhooks', '0047_merge_20250712_1657'),
    ]

    operations = [
    ]
