# Generated by Django 5.2.4 on 2025-07-14 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0048_leadpendingtask_text'),
        ('webhooks', '0048_merge_20250714_1749'),
    ]

    operations = [
    ]
