# Generated by Django 5.2.4 on 2025-07-14 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0049_leadpendingtask_unique_condition'),
        ('webhooks', '0049_merge_20250714_2259'),
    ]

    operations = [
    ]
