# Generated by Django 5.2.4 on 2025-07-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0050_drop_scheduled_models'),
        ('webhooks', '0050_merge_20250714_2307'),
    ]

    operations = [
    ]
