# Generated by Django 5.2.4 on 2025-07-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0051_leadevent_follow_up_unique'),
        ('webhooks', '0051_merge_20250716_1148'),
    ]

    operations = [
    ]
