# Generated by Django 5.2.4 on 2025-07-21 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0052_merge_20250716_1238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutoResponseSettingsTemplate',
        ),
    ]
