# Generated by Django 5.2.4 on 2025-07-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0052_leadevent_from_backend'),
        ('webhooks', '0053_delete_autoresponsesettingstemplate'),
    ]

    operations = [
    ]
