# Generated by Django 5.2.4 on 2025-07-22 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0053_remove_autoresponsesettings_follow_up'),
        ('webhooks', '0054_merge_20250722_1043'),
    ]

    operations = [
    ]
