# Generated by Django 5.2.4 on 2025-07-22 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0054_autoresponsesettings_open_days'),
        ('webhooks', '0055_merge_20250722_1059'),
    ]

    operations = [
    ]
