# Generated by Django 5.2.4 on 2025-07-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0056_merge_20250722_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoresponsesettings',
            name='greeting_open_days',
            field=models.CharField(blank=True, help_text="Скорочені назви днів тижня через кому, напр. 'Mon, Tue, Wed'", max_length=64),
        ),
    ]
