# Generated by Django 5.2.4 on 2025-07-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0055_notification_setting'),
        ('webhooks', '0057_alter_autoresponsesettings_greeting_open_days'),
    ]

    operations = [
    ]
