# Generated by Django 5.2.4 on 2025-07-23 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0056_notification_unique_phone'),
        ('webhooks', '0058_merge_20250723_1150'),
    ]

    operations = [
    ]
