# Generated by Django 5.2.4 on 2025-07-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0059_merge_20250723_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsetting',
            name='message_template',
            field=models.TextField(help_text='Text with placeholders {business_id}, {lead_id}, {business_name}, {timestamp}, {phone}'),
        ),
    ]
