# Generated by Django 5.2.4 on 2025-07-24 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0057_notification_business'),
        ('webhooks', '0060_alter_notificationsetting_message_template'),
    ]

    operations = [
    ]
