# Generated by Django 5.2.4 on 2025-07-24 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0061_merge_20250724_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsetting',
            name='business',
            field=models.ForeignKey(blank=True, help_text='Business for this setting. Null → global', null=True, on_delete=django.db.models.deletion.CASCADE, to='webhooks.yelpbusiness'),
        ),
    ]
