# Generated by Django 5.2.4 on 2025-07-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0059_smslog'),
        ('webhooks', '0062_alter_notificationsetting_business'),
    ]

    operations = [
    ]
