# Generated by Django 5.2.4 on 2025-07-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0063_merge_20250725_1127'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='smslog',
            new_name='webhooks_sm_busines_db11fc_idx',
            old_name='webhooks_smslog_bus_sent_idx',
        ),
        migrations.RenameIndex(
            model_name='smslog',
            new_name='webhooks_sm_lead_id_1a16ff_idx',
            old_name='webhooks_smslog_lead_sent_idx',
        ),
        migrations.RenameIndex(
            model_name='smslog',
            new_name='webhooks_sm_purpose_c561e2_idx',
            old_name='webhooks_smslog_purpose_sent_idx',
        ),
        migrations.RenameIndex(
            model_name='smslog',
            new_name='webhooks_sm_status_47e0cf_idx',
            old_name='webhooks_smslog_status_sent_idx',
        ),
    ]
