# Generated by Django 5.2.4 on 2025-07-29 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0060_ai_settings_and_fields'),
        ('webhooks', '0064_rename_webhooks_smslog_bus_sent_idx_webhooks_sm_busines_db11fc_idx_and_more'),
    ]

    operations = [
    ]
