# Generated by Django 5.2.4 on 2025-07-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0065_merge_20250729_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisettings',
            name='always_use_customer_name',
            field=models.BooleanField(default=True, help_text="Завжди використовувати ім'я клієнта, якщо доступне"),
        ),
    ]
