# Generated by Django 5.2.4 on 2025-07-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0066_alter_aisettings_always_use_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoresponsesettings',
            name='ai_include_address',
            field=models.BooleanField(default=False, help_text='Включати повну адресу в AI повідомлення'),
        ),
        migrations.AddField(
            model_name='autoresponsesettings',
            name='ai_include_categories',
            field=models.BooleanField(default=True, help_text='Включати категорії/спеціалізацію бізнесу в AI повідомлення'),
        ),
        migrations.AddField(
            model_name='autoresponsesettings',
            name='ai_include_hours',
            field=models.BooleanField(default=True, help_text='Включати інформацію про робочі години в AI повідомлення'),
        ),
        migrations.AddField(
            model_name='autoresponsesettings',
            name='ai_include_phone',
            field=models.BooleanField(default=True, help_text='Включати телефон бізнесу в AI повідомлення'),
        ),
        migrations.AddField(
            model_name='autoresponsesettings',
            name='ai_include_price_range',
            field=models.BooleanField(default=True, help_text='Включати ціновий діапазон ($-$$$$) в AI повідомлення'),
        ),
        migrations.AddField(
            model_name='autoresponsesettings',
            name='ai_include_rating',
            field=models.BooleanField(default=True, help_text='Включати рейтинг бізнесу в AI повідомлення'),
        ),
        migrations.AddField(
            model_name='autoresponsesettings',
            name='ai_include_reviews_count',
            field=models.BooleanField(default=True, help_text='Включати кількість відгуків в AI повідомлення'),
        ),
        migrations.AddField(
            model_name='autoresponsesettings',
            name='ai_include_transactions',
            field=models.BooleanField(default=False, help_text='Включати доступні послуги/транзакції в AI повідомлення'),
        ),
        migrations.AddField(
            model_name='autoresponsesettings',
            name='ai_include_website',
            field=models.BooleanField(default=False, help_text='Включати веб-сайт бізнесу в AI повідомлення'),
        ),
    ]
