# Generated by Django 5.2.4 on 2025-07-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0067_autoresponsesettings_ai_include_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoresponsesettings',
            name='ai_max_message_length',
            field=models.PositiveIntegerField(default=160, help_text='Максимальна довжина AI-згенерованого повідомлення (символів). Якщо 0 - використовується глобальне налаштування'),
        ),
    ]
