# Generated by Django 5.2.4 on 2025-08-04 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0061_remove_phone_in_dialog_field'),
        ('webhooks', '0068_autoresponsesettings_ai_max_message_length'),
    ]

    operations = [
    ]
