# Generated by Django 5.2.4 on 2025-08-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0069_merge_20250804_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoresponsesettings',
            name='sms_on_customer_reply',
            field=models.BooleanField(default=True, help_text='Відправляти SMS коли клієнт відповідає на повідомлення'),
        ),
        migrations.AddField(
            model_name='autoresponsesettings',
            name='sms_on_phone_found',
            field=models.BooleanField(default=True, help_text='Відправляти SMS коли система знаходить номер телефону в тексті'),
        ),
        migrations.AddField(
            model_name='autoresponsesettings',
            name='sms_on_phone_opt_in',
            field=models.BooleanField(default=True, help_text='Відправляти SMS коли приходить phone opt-in від клієнта'),
        ),
    ]
