# Generated by Django 5.2.5 on 2025-09-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0063_create_default_greetings'),
        ('webhooks', '0071_timebasedgreeting'),
    ]

    operations = [
    ]
