# Generated by Django 5.2.5 on 2025-09-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0072_merge_20250902_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(help_text='Оригінальна назва послуги, яка приходить з Yelp', max_length=200, unique=True)),
                ('custom_name', models.CharField(help_text='Ваша власна назва для цієї послуги', max_length=200)),
                ('active', models.BooleanField(default=True, help_text='Чи активна ця заміна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Name Mapping',
                'verbose_name_plural': 'Job Name Mappings',
                'ordering': ['original_name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='leadpendingtask',
            name='uniq_lead_text',
        ),
        migrations.RemoveField(
            model_name='timebasedgreeting',
            name='afternoon_casual',
        ),
        migrations.RemoveField(
            model_name='timebasedgreeting',
            name='afternoon_formal',
        ),
        migrations.RemoveField(
            model_name='timebasedgreeting',
            name='default_style',
        ),
        migrations.RemoveField(
            model_name='timebasedgreeting',
            name='evening_casual',
        ),
        migrations.RemoveField(
            model_name='timebasedgreeting',
            name='evening_formal',
        ),
        migrations.RemoveField(
            model_name='timebasedgreeting',
            name='morning_casual',
        ),
        migrations.RemoveField(
            model_name='timebasedgreeting',
            name='morning_formal',
        ),
        migrations.AddField(
            model_name='autoresponsesettings',
            name='ai_model',
            field=models.CharField(blank=True, default='', help_text='OpenAI модель для цього бізнесу (якщо порожня - використовується глобальна)', max_length=50),
        ),
        migrations.AddField(
            model_name='autoresponsesettings',
            name='ai_temperature',
            field=models.FloatField(blank=True, help_text='Temperature для AI генерації цього бізнесу (якщо порожня - використовується глобальна)', null=True),
        ),
        migrations.AddField(
            model_name='leaddetail',
            name='customer_replied',
            field=models.BooleanField(default=False, help_text='Customer has already replied at least once (to prevent repeated Customer Reply SMS)'),
        ),
        migrations.AddField(
            model_name='leaddetail',
            name='phone_sms_sent',
            field=models.BooleanField(default=False, help_text='Any SMS notification has already been sent for this lead (to prevent duplicate SMS)'),
        ),
        migrations.AddField(
            model_name='timebasedgreeting',
            name='afternoon_greeting',
            field=models.CharField(default='Good afternoon', help_text='Afternoon greeting', max_length=100),
        ),
        migrations.AddField(
            model_name='timebasedgreeting',
            name='evening_greeting',
            field=models.CharField(default='Good evening', help_text='Evening greeting', max_length=100),
        ),
        migrations.AddField(
            model_name='timebasedgreeting',
            name='morning_greeting',
            field=models.CharField(default='Good morning', help_text='Morning greeting', max_length=100),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='base_system_prompt',
            field=models.TextField(default='You are a professional business communication assistant. Generate personalized, friendly, and professional greeting messages for potential customers who have inquired about services.', help_text='Fallback системний промпт для AI (коли не вказаний кастомний промпт для бізнесу)'),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='default_temperature',
            field=models.FloatField(default=0.7, help_text='Fallback temperature для AI генерації (коли не вказана для бізнесу)'),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='max_message_length',
            field=models.PositiveIntegerField(default=160, help_text='Fallback максимальна довжина повідомлення (коли не вказана для бізнесу)'),
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='openai_model',
            field=models.CharField(default='gpt-4o', help_text='Fallback модель OpenAI (коли не вказана для бізнесу)', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='leadpendingtask',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True), models.Q(('text', ''), _negated=True)), fields=('lead_id', 'text'), name='uniq_lead_text_active'),
        ),
    ]
