# Generated by Django 5.2.5 on 2025-09-04 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0073_jobmapping_remove_leadpendingtask_uniq_lead_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoresponsesettings',
            name='phone_opt_in',
        ),
        migrations.RemoveField(
            model_name='followuptemplate',
            name='phone_opt_in',
        ),
    ]
