# Generated by Django 5.2.5 on 2025-09-04 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0074_remove_autoresponsesettings_phone_opt_in_and_more'),
        ('webhooks', '0074_remove_phone_optin_duplicates'),
    ]

    operations = [
    ]
