# Generated by Django 5.2.6 on 2025-09-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0076_remove_leadpendingtask_phone_opt_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerytasklog',
            name='sent_at',
            field=models.DateTimeField(blank=True, help_text='Real time when message was sent to Yelp API', null=True),
        ),
        migrations.CreateModel(
            name='LeadActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(db_index=True, max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('activity_type', models.CharField(choices=[('WEBHOOK', 'Webhook Processing'), ('PLANNING', 'Follow-up Planning'), ('EXECUTION', 'Message Execution'), ('ANALYSIS', 'Event Analysis'), ('ERROR', 'Error Handling')], db_index=True, max_length=50)),
                ('component', models.CharField(choices=[('BACKEND', 'Django Backend'), ('WORKER', 'RQ Worker'), ('SCHEDULER', 'RQ Scheduler'), ('API', 'API Request')], max_length=30)),
                ('event_name', models.CharField(help_text='Function or event name', max_length=100)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('business_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['lead_id', '-timestamp'], name='webhooks_le_lead_id_bc0331_idx'), models.Index(fields=['activity_type', '-timestamp'], name='webhooks_le_activit_e82175_idx'), models.Index(fields=['business_id', '-timestamp'], name='webhooks_le_busines_14dfcd_idx'), models.Index(fields=['task_id', '-timestamp'], name='webhooks_le_task_id_ef7995_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('error_type', models.CharField(choices=[('API_ERROR', 'API Communication Error'), ('DJANGO_ERROR', 'Django Application Error'), ('TASK_ERROR', 'RQ Task Execution Error'), ('TOKEN_ERROR', 'Token/Authentication Error'), ('DATABASE_ERROR', 'Database Operation Error'), ('TIMING_ERROR', 'Follow-up Timing Error'), ('WEBHOOK_ERROR', 'Webhook Processing Error'), ('VALIDATION_ERROR', 'Data Validation Error')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('LOW', 'Low - Informational'), ('MEDIUM', 'Medium - Warning'), ('HIGH', 'High - Error'), ('CRITICAL', 'Critical - System Down')], db_index=True, default='MEDIUM', max_length=20)),
                ('component', models.CharField(max_length=50)),
                ('function_name', models.CharField(blank=True, max_length=100)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField()),
                ('exception_type', models.CharField(blank=True, max_length=100)),
                ('traceback', models.TextField(blank=True)),
                ('lead_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('business_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['-timestamp'], name='webhooks_sy_timesta_5fd10a_idx'), models.Index(fields=['error_type', '-timestamp'], name='webhooks_sy_error_t_c8805b_idx'), models.Index(fields=['severity', '-timestamp'], name='webhooks_sy_severit_44def5_idx'), models.Index(fields=['lead_id', '-timestamp'], name='webhooks_sy_lead_id_97e7f3_idx'), models.Index(fields=['resolved', '-timestamp'], name='webhooks_sy_resolve_2c9bad_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemHealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metric_type', models.CharField(choices=[('API_RESPONSE_TIME', 'API Response Time'), ('FOLLOW_UP_SUCCESS_RATE', 'Follow-up Success Rate'), ('QUEUE_LENGTH', 'RQ Queue Length'), ('DATABASE_QUERY_TIME', 'Database Query Time'), ('YELP_API_SUCCESS_RATE', 'Yelp API Success Rate'), ('TOKEN_REFRESH_RATE', 'Token Refresh Rate'), ('MEMORY_USAGE', 'Memory Usage'), ('ACTIVE_LEADS', 'Active Leads Count')], db_index=True, max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(default='count', max_length=20)),
                ('component', models.CharField(blank=True, max_length=50)),
                ('business_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['metric_type', '-timestamp'], name='webhooks_sy_metric__3e3c4b_idx'), models.Index(fields=['-timestamp'], name='webhooks_sy_timesta_e9385c_idx')],
            },
        ),
    ]
