# Generated by Django 4.2.x
from django.db import migrations, models
from django.db.models import Q

class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0077_job_mapping'),
    ]

    operations = [
        # Видаляємо старий constraint
        migrations.RemoveConstraint(
            model_name='leadpendingtask',
            name='uniq_lead_text',
        ),
        
        # Додаємо новий constraint що діє тільки для активних записів
        migrations.AddConstraint(
            model_name='leadpendingtask',
            constraint=models.UniqueConstraint(
                fields=['lead_id', 'text'],
                condition=Q(active=True) & ~Q(text=""),
                name='uniq_lead_text_active'
            ),
        ),
    ]
