# Generated by Django 5.2.6 on 2025-09-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0037_add_vector_models'),
        ('webhooks', '0077_celerytasklog_sent_at_leadactivitylog_systemerrorlog_and_more'),
    ]

    operations = [
    ]
