# Generated by Django 4.2.x
from django.db import migrations, models
from django.db.models import Q

class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0077_job_mapping'),
    ]

    operations = [
        # Безпечно видаляємо старий constraint якщо існує
        migrations.RunSQL(
            sql="ALTER TABLE webhooks_leadpendingtask DROP CONSTRAINT IF EXISTS uniq_lead_text;",
            reverse_sql="-- Cannot reverse this operation automatically",
        ),
        
        # Безпечно додаємо новий constraint тільки якщо не існує
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN 
                    IF NOT EXISTS (
                        SELECT 1 FROM pg_constraint 
                        WHERE conname = 'uniq_lead_text_active'
                    ) THEN
                        ALTER TABLE webhooks_leadpendingtask 
                        ADD CONSTRAINT uniq_lead_text_active 
                        UNIQUE (lead_id, text) 
                        WHERE (active = true AND text <> '');
                    END IF;
                END $$;
            """,
            reverse_sql="ALTER TABLE webhooks_leadpendingtask DROP CONSTRAINT IF EXISTS uniq_lead_text_active;",
        ),
    ]
