# Generated by Django 5.2.6 on 2025-09-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0078_merge_20250928_1538'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VectorChunk',
        ),
        migrations.DeleteModel(
            name='VectorDocument',
        ),
    ]
