# Generated by Django 5.2.6 on 2025-09-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0079_delete_vectorchunk_delete_vectordocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoresponsesettings',
            name='vector_chunk_types',
            field=models.JSONField(blank=True, default=list, help_text="Типи чанків для пошуку: ['inquiry', 'response', 'example', 'general']. Порожній список = всі типи"),
        ),
        migrations.AddField(
            model_name='autoresponsesettings',
            name='vector_search_limit',
            field=models.PositiveIntegerField(default=5, help_text='Максимальна кількість результатів vector search'),
        ),
        migrations.AddField(
            model_name='autoresponsesettings',
            name='vector_similarity_threshold',
            field=models.FloatField(default=0.6, help_text='Поріг семантичної схожості для vector search (0.0-1.0). Нижчі значення дають більше результатів'),
        ),
    ]
