# Generated by Django 5.2.6 on 2025-09-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0080_autoresponsesettings_vector_chunk_types_and_more'),
        ('webhooks', '0080_change_vector_similarity_threshold_default'),
    ]

    operations = [
    ]
