# Generated by Django 4.2.24 on 2025-10-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0081_merge_20250929_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoresponsesettings',
            name='ai_response_style',
        ),
        migrations.AlterField(
            model_name='autoresponsesettings',
            name='vector_similarity_threshold',
            field=models.FloatField(default=0.4, help_text='Поріг семантичної схожості для vector search (0.0-1.0). Нижчі значення дають більше результатів'),
        ),
    ]
