# Generated by Django 4.2.25 on 2025-10-08 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0081_add_message_queue_fields'),
        ('webhooks', '0082_remove_autoresponsesettings_ai_response_style_and_more'),
    ]

    operations = [
    ]
