# Generated by Django 4.2.25 on 2025-10-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0083_merge_20251008_1049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadpendingtask',
            options={'ordering': ['lead_id', 'sequence_number']},
        ),
        migrations.RemoveField(
            model_name='autoresponsesettings',
            name='ai_include_location',
        ),
        migrations.RemoveField(
            model_name='autoresponsesettings',
            name='ai_mention_response_time',
        ),
        migrations.AlterField(
            model_name='aisettings',
            name='max_message_length',
            field=models.PositiveIntegerField(default=0, help_text='DEPRECATED: Ігнорується. Система автоматично визначає довжину з Sample Replies'),
        ),
        migrations.AlterField(
            model_name='autoresponsesettings',
            name='ai_max_message_length',
            field=models.PositiveIntegerField(default=0, help_text='DEPRECATED: Ігнорується системою. Довжина визначається автоматично з Sample Replies прикладів'),
        ),
    ]
