# Generated by Django 4.2.25 on 2025-10-22 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0084_remove_deprecated_ai_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoresponsesettings',
            name='ai_include_address',
        ),
        migrations.RemoveField(
            model_name='autoresponsesettings',
            name='ai_include_categories',
        ),
        migrations.RemoveField(
            model_name='autoresponsesettings',
            name='ai_include_hours',
        ),
        migrations.RemoveField(
            model_name='autoresponsesettings',
            name='ai_include_phone',
        ),
        migrations.RemoveField(
            model_name='autoresponsesettings',
            name='ai_include_price_range',
        ),
        migrations.RemoveField(
            model_name='autoresponsesettings',
            name='ai_include_rating',
        ),
        migrations.RemoveField(
            model_name='autoresponsesettings',
            name='ai_include_reviews_count',
        ),
        migrations.RemoveField(
            model_name='autoresponsesettings',
            name='ai_include_transactions',
        ),
        migrations.RemoveField(
            model_name='autoresponsesettings',
            name='ai_include_website',
        ),
    ]
