# Generated by Django 4.2.25 on 2025-10-23 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0085_remove_ai_include_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoresponsesettings',
            name='whatsapp_on_customer_reply',
            field=models.BooleanField(default=True, help_text='Відправляти WhatsApp коли клієнт відповідає на повідомлення'),
        ),
        migrations.AddField(
            model_name='autoresponsesettings',
            name='whatsapp_on_phone_found',
            field=models.BooleanField(default=True, help_text='Відправляти WhatsApp коли система знаходить номер телефону в тексті'),
        ),
        migrations.AddField(
            model_name='autoresponsesettings',
            name='whatsapp_on_phone_opt_in',
            field=models.BooleanField(default=True, help_text='Відправляти WhatsApp коли приходить phone opt-in від клієнта'),
        ),
        migrations.CreateModel(
            name='WhatsAppNotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=64)),
                ('message_template', models.TextField(help_text='Text with placeholders {business_id}, {lead_id}, {business_name}, {timestamp}, {phone}')),
                ('business', models.ForeignKey(blank=True, help_text='Business for this setting. Null → global', null=True, on_delete=django.db.models.deletion.CASCADE, to='webhooks.yelpbusiness')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(db_index=True, help_text='Twilio Message SID', max_length=128, unique=True)),
                ('to_phone', models.CharField(db_index=True, help_text='Destination phone number', max_length=32)),
                ('from_phone', models.CharField(help_text='Source phone number (Twilio WhatsApp)', max_length=32)),
                ('body', models.TextField(help_text='WhatsApp message content')),
                ('lead_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('business_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('purpose', models.CharField(blank=True, help_text='notification, auto_response, manual, api', max_length=50)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('price_unit', models.CharField(blank=True, max_length=10, null=True)),
                ('direction', models.CharField(blank=True, max_length=20, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('twilio_created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['business_id', '-sent_at'], name='webhooks_wh_busines_e3d822_idx'), models.Index(fields=['lead_id', '-sent_at'], name='webhooks_wh_lead_id_d3eef1_idx'), models.Index(fields=['purpose', '-sent_at'], name='webhooks_wh_purpose_d24c6f_idx'), models.Index(fields=['status', '-sent_at'], name='webhooks_wh_status_735244_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='whatsappnotificationsetting',
            constraint=models.UniqueConstraint(fields=('business', 'phone_number'), name='uniq_whatsapp_notification_business_phone'),
        ),
    ]
