# Generated by Django 4.2.25 on 2025-10-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0086_autoresponsesettings_whatsapp_on_customer_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappnotificationsetting',
            name='content_name',
            field=models.CharField(blank=True, help_text='Template friendly name', max_length=255),
        ),
        migrations.AddField(
            model_name='whatsappnotificationsetting',
            name='content_sid',
            field=models.CharField(blank=True, help_text='Twilio Content SID (HX...)', max_length=64),
        ),
        migrations.AddField(
            model_name='whatsappnotificationsetting',
            name='use_content_template',
            field=models.BooleanField(default=False, help_text='Use Twilio Content Template instead of simple template'),
        ),
        migrations.AddField(
            model_name='whatsappnotificationsetting',
            name='variable_mapping',
            field=models.JSONField(default=dict, help_text="Maps template variables: {'1': 'business_id', '2': 'lead_id', ...}"),
        ),
        migrations.AlterField(
            model_name='whatsappnotificationsetting',
            name='message_template',
            field=models.TextField(help_text='Simple template with {business_id}, {lead_id}, {business_name}, {timestamp}, {phone}'),
        ),
    ]
