# Generated by Django 4.2.25 on 2025-10-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0087_add_whatsapp_content_template_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappnotificationsetting',
            name='message_template',
            field=models.TextField(blank=True, help_text='Simple template with {business_id}, {lead_id}, {business_name}, {timestamp}, {phone}'),
        ),
    ]
