# Generated by Django 4.2.25 on 2025-10-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0088_allow_empty_message_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappnotificationsetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappnotificationsetting',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Enable or disable this WhatsApp notification'),
        ),
        migrations.AddField(
            model_name='whatsappnotificationsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
