# Generated by Django 4.2.25 on 2025-10-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0089_whatsappnotificationsetting_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappnotificationsetting',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
