# Generated by Django 4.2.25 on 2025-10-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0090_alter_whatsappnotificationsetting_phone_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='whatsappnotificationsetting',
            name='uniq_whatsapp_notification_business_phone',
        ),
        migrations.AddConstraint(
            model_name='whatsappnotificationsetting',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_number__gt', '')), fields=('business', 'phone_number'), name='uniq_whatsapp_notification_business_phone'),
        ),
        migrations.AddConstraint(
            model_name='whatsappnotificationsetting',
            constraint=models.UniqueConstraint(condition=models.Q(('content_sid__gt', ''), ('use_content_template', True)), fields=('business', 'content_sid'), name='uniq_whatsapp_notification_business_content'),
        ),
    ]
