# Generated by Django 4.2.25 on 2025-10-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0091_remove_whatsappnotificationsetting_uniq_whatsapp_notification_business_phone_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='whatsappnotificationsetting',
            name='uniq_whatsapp_notification_business_phone',
        ),
        migrations.RemoveConstraint(
            model_name='whatsappnotificationsetting',
            name='uniq_whatsapp_notification_business_content',
        ),
        migrations.AddConstraint(
            model_name='whatsappnotificationsetting',
            constraint=models.UniqueConstraint(condition=models.Q(('content_sid__gt', ''), ('use_content_template', True)), fields=('business', 'content_sid', 'phone_number'), name='uniq_whatsapp_content_business_phone'),
        ),
        migrations.AddConstraint(
            model_name='whatsappnotificationsetting',
            constraint=models.UniqueConstraint(condition=models.Q(('use_content_template', False)), fields=('business', 'phone_number'), name='uniq_whatsapp_simple_business_phone'),
        ),
    ]
