# Generated by Django 4.2.25 on 2025-10-27 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0082_add_ai_generation_fields'),
        ('webhooks', '0092_update_whatsapp_phone_constraints'),
    ]

    operations = [
    ]
