# Generated by Django 4.2.25 on 2025-11-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0093_merge_20251027_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='yelpbusiness',
            name='representative_name',
            field=models.CharField(blank=True, default='', help_text="ОБОВ'ЯЗКОВЕ: Ім'я представника для підпису AI повідомлень (напр. 'Developer D.', 'John Smith'). AI використає ТЕ ім'я для підпису замість плейсхолдерів.", max_length=100),
        ),
    ]
